### ISSUE TITLE
Duplicate R119 on latest control_rev3 schematic

### ISSUE THREAD

**Issue by EddieHorn** [PaulStoffregen/O_C_T41#1]
[control_rev3.pdf](https://github.com/user-attachments/files/16281441/control_rev3.pdf)
Hi Paul, Great work on the 4.1 board. I was looking at the schematic and noticed duplicate numbers for R119. I've marked them on attached .pdf

Best Regards
Eddie

**Comment by PaulStoffregen** [comment]
Opps, the resistor connected to the opamp is really R118.

Fixed: https://github.com/PaulStoffregen/O_C_T41/commit/ca44bec0c4f43e6e52b65ad631a0cd9bf04813c8

**Comment by PaulStoffregen** [comment]
PDF updated: https://github.com/PaulStoffregen/O_C_T41/commit/0aa44c64ca89e6f59608df03b721c48f74730e6b
